use crate::prelude::*;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EditorEvent {
    NoOp,
    ToggleSegmentOnSelectedGlyph(Segment),
    ToggleSegmentsOnSelectedGlyph(Vec<Segment>),
    MoveWordsViewSliceBackward(usize),
    MoveWordsViewSliceForward(usize),
    MoveGlyphCursorForward,
    MoveGlyphCursorBackward,
    MoveWordCursorForward,
    MoveWordCursorBackward,
    MoveSnippetCursorForward,
    MoveSnippetCursorBackward,
    AddNewTunicWordAtCursor,
    AddNewEnglishWordAtCursor(String),
    AddNewGlyphToTunicWordAtCursor,
    AddNewSnippetAtCursor,
    DeleteGlyphAtCursor,
    DeleteWordAtCursor,
    RequestLoadFromFile,
    RequestSaveToFile,
    ConfirmLoadFromFileRequest,
    ConfirmSaveToFileRequest,
    ReportLoadedFromFile(Notebook),
    ReportSavedToFile,
    ReportFailedToLoadFromFile(FileEditorError),
    ReportFailedToSaveToFile(FileEditorError),
    ResetFileEditorToIdle,
    EnableSnippetNavigationMode,
    EnableSnippetEditingMode,
    ToggleSnippetTranscriptionState,
    ToggleHasBeenTranscribedFilter,
    ToggleWordHasABorderState,
    ToggleWordIsColoredState,
    PrintWord(Word),
}
